"""add isActive status

Revision ID: 23cb1ec6c763
Revises: 1bc885bb67c3
Create Date: 2025-04-09 16:01:47.573738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cb1ec6c763'
down_revision = '1bc885bb67c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isActive')

    # ### end Alembic commands ###
