"""add isActive

Revision ID: cc1f9b213fb5
Revises: 8d5b345dbb08
Create Date: 2025-04-22 16:29:13.441866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc1f9b213fb5'
down_revision = '8d5b345dbb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=True))
        batch_op.drop_column('isActive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('isActive')

    # ### end Alembic commands ###
